### ISSUE TITLE
付费报告的BUG貌似修复了

### ISSUE THREAD

**Issue by Paomiantong** [anwenhu/zhixuewang-python#17]
https://www.zhixue.com/zhixuebao/zhixuebao/feesReport/getStuSingleReportDataForPK/

提示{"errorCode":1111,"errorInfo":"没有权限访问","result":""}

**Comment by Gaomengkai** [comment]
查成绩也是没有权限访问 以下是json解析过的数据
 {'errorCode': 1111, 'errorInfo': '没有权限访问', 'result': ''},

**Comment by Gaomengkai** [comment]
Since this 
`GET_MARK_URL = f"{BASE_URL}/zhixuebao/zhixuebao/feesReport/getStuSingleReportDataForPK/"` guale,
we can get students' rank in this page:
`GET_PAPERID_URL = f"{BASE_URL}/zhixuebao/report/exam/getReportMain"`
But it contains little information. With class/grade avg/high/low cannot be seen, it may the only temporary way to substitute before we find new methods.

**Comment by anwenhu** [comment]
的确, 现在只能获取到成绩了
